# Generated by Django 2.2.20 on 2022-07-16 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=50)),
                ('problem_desc', models.TextField()),
                ('problem_difficulty', models.CharField(choices=[('difficult', 'difficult'), ('medium', 'medium'), ('easy', 'easy')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.FileField(upload_to='test_inputs/')),
                ('test_output', models.FileField(upload_to='test_outputs/')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('c++', 'cpp')], max_length=10)),
                ('code_file', models.FileField(upload_to='code_file/')),
                ('verdict', models.CharField(choices=[('PS', 'Processing'), ('WA', 'Wrong Answer'), ('AC', 'All Correct')], max_length=5)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
